// vue/src/views/StateManagement.vue
<template>
    <div>
      <Main/>
      <Navbar/>
    </div>
</template>

<script>
import Main from '../components/stateManagement/Main'
import Navbar from '../components/stateManagement/Navbar'
export default {
  name: 'StateManagement',
  components: { Navbar, Main }
}
</script>

<style scoped>

</style>

// react-/src/components/stateManagement/stateManagement.js
import React , {Component} from "react";
import Main from "./Main";
import Navbar from "./Navbar";

class StateManagement extends Component{
    render() {
        return (
            <div>
                <Main/>
                <Navbar/>
            </div>
        )
    }
}

export default StateManagement;
