// vue/src/views/checkboxWrapper.vue
<template>
  <div>
<!-- <div>    <button v-on:click="addMoreCheckBox">add 500 checkbox</button> -->
<!-- </div>    -->
    <!-- <Checkbox v-for="(element , index) in elements "  v-bind:id="index">

         <img src="../assets/logo.png" alt="" class="img-logo">
         {{index}}
       </Checkbox>  -->
     <Checkbox v-model="value" id="2">

       <img src="../assets/logo.png" alt="" class="img-logo">
     aaaa
      </Checkbox>
  </div>
</template>

<script>
import Checkbox from '../components/checkbox'
export default {
  name: 'checkboxWrapper',
  components: { Checkbox },
  data: function () {
    return {
      value: false,
      value1: false,
      value2: true,
      elements: new Array(0)
    }
  },
  methods: {
    addMoreCheckBox () {
      this.elements = new Array(500)
    }
  }
}
</script>

<style scoped>
  .img-logo{
    height: 50px;
  }
</style>

// react-/src/components/checkboxWrapper/checkboxWrapper.js
import React, { Component } from 'react';
import Checkbox from "./checkbox";
import logo from '../../logo.svg';
import Textholder from '../textholder'
class CheckboxWrapper extends Component {
    constructor(props) {
        super(props);
        this.valueChangeFirst = this.valueChangeFirst.bind(this);
        this.valueChangeSecond = this.valueChangeSecond.bind(this)
        this.valueChangeThird = this.valueChangeThird.bind(this)
        this.addMoreCheckbox = this.addMoreCheckbox.bind(this)
    }

    state = {
        valueFirst: true,
        valueSecond:false,
        valueThird:true ,
         data : new Array(0)
    };

    valueChangeFirst (e) {
        this.setState({valueFirst: e});
        alert("value")
    }
    valueChangeSecond (e) {
        this.setState({valueSecond: e});
        alert("value")
    }
    valueChangeThird (e) {
        this.setState({valueThird: e});
        alert("value")
    }
    addMoreCheckbox(){
this.setState(
    this.state.data = new Array(500)
      
)
    }
    render() {
      

        for (let i = 0; i < this.state.data.length; i++) {
             this.state.data[i] =   <Checkbox> {i}</Checkbox> ;
            
        }

        return (
            <div className="App">
           <button onClick={this.addMoreCheckbox}>add 500 checkbox</button>
                {/* <div>{this.state.value.toString()}</div> */}
                {/* <Checkbox  id="first"> */}
                    {/*<img style={{width: '100px'}} src={logo} className="App-logo" alt="logo" />*/}
             
                    {/* <Textholder fname="gholi"/> */}
                {/* </Checkbox> */}
                
                
                {this.state.data}
            </div>
        );
    }
}
export default CheckboxWrapper;
